language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xlabshareddocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xlabshareddocker/docker-react npm run test -- --coverage