# Use an existing docker image as a base
FROM node:alpine
WORKDIR /app

# Download and install a dependency
COPY ./package.json ./
RUN npm install

# Copy existing file structure to container
COPY . .

# Tell the image what to do when it starts as a container
CMD ["npm", "run", "start"]